service: my-serverless-service
provider:
  name: aws
  runtime: nodejs12.x
functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get

  # Logging Functions    
  loginUser:
    handler: src/handlers/loggingHandler.loginUser
    timeout: 30
    events:
      - http:
          path: loginUser
          method: post
          cors:
            origin: "http://localhost:3001"
            headers:
              - Content-Type
              - X-Custom-Header
      
  logoutUser:
    handler: src/handlers/loggingHandler.logoutUser
    timeout: 30
    events:
      - http:
          path: logoutUser
          method: post
          cors:
            origin: "http://localhost:3001"
            headers:
              - Content-Type
              - X-Custom-Header

  # Job Functions


plugins:
  - serverless-offline